//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTrackerEntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associate_Skills
    {
        public long ID { get; set; }
        public long Associate_ID { get; set; }
        public long Skill_ID { get; set; }
        public long Skill_Score { get; set; }
    
        public virtual Associate Associate { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
